/**
 * Remotion Root — Escola dos Véus
 *
 * Entry point for Remotion rendering.
 *
 * To render a video:
 *   npx remotion render Root VideoComposition --props='path/to/manifest.json'
 *
 * To preview in browser:
 *   npx remotion studio
 *
 * Note: Requires `remotion` and `@remotion/cli` packages.
 * Install: npm i remotion @remotion/cli @remotion/bundler
 */

import React from "react";
import { VideoComposition, calculateTotalFrames, FPS } from "./VideoComposition";
import type { VideoManifest } from "./VideoComposition";

// Dynamic Remotion import — compiles even without remotion installed
let Composition: React.FC<{
  id: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: React.FC<any>;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  defaultProps: VideoManifest;
}>;

let REMOTION_AVAILABLE = false;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const remotion = require("remotion");
  Composition = remotion.Composition;
  REMOTION_AVAILABLE = true;
} catch {
  // Remotion not installed
}

/**
 * Default props for preview/development.
 * In production, props come from the manifest JSON generated by produce-video API.
 */
const defaultManifest: VideoManifest = {
  courseSlug: "ouro-proprio",
  title: "Porque sentes culpa quando gastas dinheiro em ti mesma?",
  sceneLabel: "yt-hook0",
  audioUrl: "",
  backgroundMusicUrl: "https://tdytdamtfillqyklgrmb.supabase.co/storage/v1/object/public/audios/albums/curso-ouro-proprio/faixa-01.mp3",
  backgroundMusicVolume: 0.12,
  scenes: [
    {
      type: "abertura",
      narration: "",
      overlayText: "Porque sentes culpa quando gastas dinheiro em ti mesma?",
      durationSec: 12,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "pergunta",
      narration: "Quando foi a ultima vez que compraste algo so para ti?",
      overlayText: "Quando foi a ultima vez?",
      durationSec: 25,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "situacao",
      narration: "Imagina esta cena. E sabado. Estas no centro comercial.",
      overlayText: "",
      durationSec: 120,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "revelacao",
      narration: "Ha um padrao aqui que quase ninguem ve.",
      overlayText: "Gastar nos outros e generosidade.\nGastar em ti e egoismo.",
      durationSec: 130,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "gesto",
      narration: "Quero propor-te uma coisa pequena.",
      overlayText: "Para. Sente. Paga.",
      durationSec: 55,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "frase_final",
      narration: "O dinheiro que gastas em ti nao e um luxo.",
      overlayText: "O dinheiro que gastas em ti\nnao e um luxo.\nE a primeira prova de que acreditas\nque mereces estar aqui.",
      durationSec: 18,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "fecho",
      narration: "",
      overlayText: "Sete Veus",
      durationSec: 8,
      imageUrl: null,
      animationUrl: null,
    },
  ],
};

/**
 * Remotion Root component.
 *
 * When Remotion is installed, registers the VideoComposition as renderable.
 * Without Remotion, returns null (composition is used as a React component directly).
 */
export const Root: React.FC = () => {
  if (!REMOTION_AVAILABLE || !Composition) {
    return null;
  }

  return (
    <Composition
      id="VideoComposition"
      component={VideoComposition}
      durationInFrames={calculateTotalFrames(defaultManifest)}
      fps={FPS}
      width={1920}
      height={1080}
      defaultProps={defaultManifest}
    />
  );
};

export { defaultManifest };
export default Root;
