/**
 * Remotion Root — Escola dos Véus
 *
 * Entry point for Remotion rendering.
 *
 * To render a video:
 *   npx remotion render Root VideoComposition --props='path/to/manifest.json'
 *
 * To preview in browser:
 *   npx remotion studio
 *
 * Note: Requires `remotion` and `@remotion/cli` packages.
 * Install: npm i remotion @remotion/cli @remotion/bundler
 */

// When Remotion is installed, uncomment these imports:
// import { Composition } from "remotion";
// import { VideoComposition, calculateTotalFrames, FPS } from "./VideoComposition";
// import type { VideoManifest } from "./VideoComposition";

/**
 * Default props for preview/development.
 * In production, props come from the manifest JSON generated by produce-video API.
 */
const defaultManifest = {
  courseSlug: "ouro-proprio",
  title: "Porque sentes culpa quando gastas dinheiro em ti mesma?",
  sceneLabel: "yt-hook0",
  audioUrl: "",
  scenes: [
    {
      type: "abertura",
      narration: "",
      overlayText: "Porque sentes culpa quando gastas dinheiro em ti mesma?",
      durationSec: 12,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "pergunta",
      narration: "Quando foi a ultima vez que compraste algo so para ti?",
      overlayText: "Quando foi a ultima vez?",
      durationSec: 25,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "situacao",
      narration: "Imagina esta cena. E sabado. Estas no centro comercial.",
      overlayText: "",
      durationSec: 120,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "revelacao",
      narration: "Ha um padrao aqui que quase ninguem ve.",
      overlayText: "Gastar nos outros e generosidade.\nGastar em ti e egoismo.",
      durationSec: 130,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "gesto",
      narration: "Quero propor-te uma coisa pequena.",
      overlayText: "Para. Sente. Paga.",
      durationSec: 55,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "frase_final",
      narration: "O dinheiro que gastas em ti nao e um luxo.",
      overlayText: "O dinheiro que gastas em ti\nnao e um luxo.\nE a primeira prova de que acreditas\nque mereces estar aqui.",
      durationSec: 18,
      imageUrl: null,
      animationUrl: null,
    },
    {
      type: "fecho",
      narration: "",
      overlayText: "Sete Veus",
      durationSec: 8,
      imageUrl: null,
      animationUrl: null,
    },
  ],
};

/**
 * Remotion Root component.
 *
 * When Remotion is installed, this registers the VideoComposition
 * as a renderable composition.
 */
export const Root: React.FC = () => {
  // When Remotion is installed, uncomment:
  // return (
  //   <Composition
  //     id="VideoComposition"
  //     component={VideoComposition}
  //     durationInFrames={calculateTotalFrames(defaultManifest)}
  //     fps={FPS}
  //     width={1920}
  //     height={1080}
  //     defaultProps={defaultManifest}
  //   />
  // );

  return null;
};

export { defaultManifest };
export default Root;
